[package]
name = "tree-sitter-uxntal"
description = "Uxn Tal Assembly grammar for tree-sitter"
version = "1.0.0"
authors = ["Amaan Qureshi <amaanq12@gmail.com>"]
license = "MIT"
readme = "bindings/rust/README.md"
keywords = ["incremental", "parsing", "uxntal"]
categories = ["parsing", "text-editors"]
repository = "https://github.com/amaanq/tree-sitter-uxntal"
edition = "2021"
autoexamples = false

build = "bindings/rust/build.rs"
include = ["bindings/rust/*", "grammar.js", "queries/*", "src/*"]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter = "~0.20.9"

[build-dependencies]
cc = "1.0"
